### ISSUE TITLE
Testing: Hierarchy module new release

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/Hierarchy#13]
Another testing issue before updating module, after a few minor tweaks and more importantly a fresh set of eyes (Thanks Avianna!)

Create hierarchies of resources for organization and display. Each hierarchy can contain multiple nested groupings, and each grouping may optionally contain objects from a selected item set.

Please test:

- Creating, updating & re-ordering hierarchies
- Creating, updating, assigning item sets & re-ordering groupings within hierarchies
- Hierarchies & groupings display and in correct order on:
   - Site page block (admin interface and actual page)
   - Public & admin side item page (for an item that belongs to an item set assigned to a grouping. Test assigning an item to multiple groupings too)
   - Public item set browse page
   - Hierarchy grouping browse page (this is the grouping-specific page you are sent to when clicking a grouping within a hierarchy from a public item/item set/page block display)
- Site-specific Hierarchy config settings under Site->Site Admin->Settings->Hierarchy:
   - Show Hierarchy label
   - Show Hierarchy resource counts
   - Combine Hierarchy resources (this should affect both the hierarchy resource counts, if config setting is activated above, and the number of resources that are returned on the hierarchy grouping browse page)
- Public pages display correctly when logged out (i.e. private itemsets are represented by [private] but not shown or linked in hierarchy tree)
- Everything looks good across various themes

Thanks!

**Comment by aviannamiller** [comment]
Generally, everything is working as anticipated, from building/modifying hierarchies to configuring and displaying them. Tested across all themes. A few notes:

With "Combine hierarchy resources" checked in site settings, the total hierarchy resource count does not match the number of resources returned on the browse page when a hierarchy contains item sets that are applied to multiple groupings. Thus, I am unsure if the number of resources returning on the top-level browse is displaying as expected with this setting turned on:
<img width="1263" alt="Screenshot of hierarchy tree next to an item browse function. The top grouping has 1075 items, while the item browse shows 1061 results." src="https://github.com/user-attachments/assets/10da56fd-dd86-46f0-baa5-5528a6acefab" />

When logged out, private item sets are still represented in the hierarchy tree by their grouping names but cannot be navigated to. I believe this is displaying correctly but am unsure if they are supposed to have a different label to indicate they are private:
<img width="450" alt="Screenshot of two hierarchy trees. Some groupings on the tree have active branches with links and item counts, while others are greyed-out text" src="https://github.com/user-attachments/assets/469fd6e7-c67a-4c1c-9d4d-1e99689f70a0" />
This is especially confusing when a site is using The Daily since that theme does not apply the same kind of link style as other themes to active hierarchy branches. Thus, the only way to truly tell that a grouping is private and thus inaccessible (besides trying to move focus to it) is if it does not include an item count, but if resource counts are disabled altogether, this is no longer relevant:
<img width="305" alt="Screenshot of two hierarchy trees on a page. The text styling across branches is homogenous, while some have item counts and others do not" src="https://github.com/user-attachments/assets/213e4415-3bb9-426e-823e-84fb85606816" />

A suggestion: on the Site Hierarchies page, it might be helpful to include some helper text that notes how, in the case of there being more than one hierarchy added to a site, the order in which the hierarchies appear on this page informs the order they will appear on the site when multiple hierarchies are added (e.g. item pages for items that appear in more than one hierarchy). The [user manual](https://omeka.org/s/docs/user-manual/modules/hierarchy/#add-a-hierarchy-to-a-site) does a good job of covering this, but this page otherwise feels a bit out of context without that info. It also feels important to note this to help create a further distinction between the ways hierarchies can be displayed (since this page's order is irrelevant to users who are only concerned with how their hierarchies are displaying in blocks on site pages, not resource blocks, in which case they are displayed according to manual page block reordering.

**Comment by matthewjmckinley** [comment]
Thanks for the feedback! I've pushed a few commits that should fix all of these issues:

1. I've refined how grouping/itemSet resources are counted so the (xxx items) count in the hierarchy should match the resources returned # on a hierarchy grouping page.
2. When logged out, groupings with private itemSets should have (Private) appended to their title. If no grouping title, it will only show (Private). Also fixed a bug where it wasn't hyperlinking certain groupings if hierarchy_show_count wasn't checked.
3. Added helper text to the Site Hierarchies page

Let me know if these are still not working correctly after pulling latest code, or if you notice anything else

**Comment by aviannamiller** [comment]
Thank you for the changes. Resource counts are now correctly attuned to results returned, and the helper text looks great.

There are some remaining issues with private item sets in hierarchies. When logged out, the (Private) label is only appearing for hierarchy grouping browse pages. The label is not appearing in resource page blocks on items/item sets or site page blocks, and groupings with private item sets are still displaying hyperlinks:
<img width="418" alt="Screenshot of two hierarchy trees on a page. Some groupings in the trees show item counts while others do not, but all groupings display as hyperlinks " src="https://github.com/user-attachments/assets/7cd490f9-bfd5-4182-be9e-20452922f980" />

Navigating to the hyperlinked page opens a hierarchy grouping browse page set to what should be the private grouping. While items do not display, the page is still navigable and hyperlinked until a different grouping is activated, in which case the hyperlink does indeed disappear:
<img width="842" alt="alt=Screenshot of hierarchy tree next to an item browse function, which displays 0 results. Some groupings, including the selected one, display with a 'Private' label" src="https://github.com/user-attachments/assets/0e45df97-bbd3-4e3f-99fe-cf1e75e52a34" />

**Comment by matthewjmckinley** [comment]
Whoops, forgot to implement across the board, and chased down some bugs to make everything match. Hopefully everything looks good with the latest commits!

**Comment by aviannamiller** [comment]
The Private labels are now appearing in all locations and private groupings generally are not hyperlinking as expected, though a different related issue has presented itself in the interim. On site page blocks, groupings that contain **both** private and public children are not hyperlinked and display as Private:
<img width="372" alt="Screenshot of two hierarchy trees on a page. Some groupings display as Private, while others are hyperlinked with visible item counts" src="https://github.com/user-attachments/assets/e76a1f56-a104-4921-8ccb-51276023c627" />
**However**, on both resource page blocks and hierarchy grouping browse pages, these kinds of groupings are hyperlinked while maintaining that Private label:
<img width="833" alt="alt=Screenshot of hierarchy tree next to an item browse function, which displays 5 results. Some groupings, including the selected one, display with a 'Private' label. The selected grouping has both a public and a Private children" src="https://github.com/user-attachments/assets/1e71bad8-9477-451b-aebf-046b5bd344f5" />
Since the collective grouping depends on the content (and thus, any restrictions that are carried) in those child groupings, which in this case is based on both private and public item sets, I think it makes sense to not make groupings that contain private children navigable (matching the way site page blocks are displaying groupings of this sort).

**Comment by allanaaa** [comment]
Small request: can you change "link" to "grouping" when something is being deleted with the trash-can button?

<img width="726" alt="Image" src="https://github.com/user-attachments/assets/5e503455-4283-4c65-a160-041cf66681e7" />

**Comment by allanaaa** [comment]
I've just updated core, this module, and all my themes, and it appears we have lost the formatting of hierarchy pages to match the other browse pages:

https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/hierarchy/56

Items in the browse table should be appearing the same way they do here (unless I'm forgetting some reason not to): 

https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item
https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item-set/35749

It's also not picking up the sort defaults we've been discussing elsewhere (in this case, it should be "Custom (dcterms:format) descending" according to my site settings).

**Comment by matthewjmckinley** [comment]
@aviannamiller latest commit should have the functionality you asked for--remove hyperlink from groupings with private and public children across the board.

@kimisgold I'm not really sure what changed to lose the formatting that @allanaaa mentions above--would you mind taking a look? Also, I looked into making the other change Allana asked for, changing 'link to be removed' to 'grouping to be removed', but it looks tied into the larger JSTree `removenode` plugin code, i.e. I'm not sure how to change that without porting over and rewriting the whole `removenode` plugin to the Hierarchy module, which I'd rather not do for such a small change. So I'm inclined to leave that out, unless you know an easier way?

**Comment by aviannamiller** [comment]
Thanks, that looks great!

**Comment by allanaaa** [comment]
I like the addition of "Private". It is working inconsistently on the Lively theme (of the 3 I've seen so far). It's appearing on item set view pages but not in the hierarchy browse pages.

<img width="1069" alt="Image" src="https://github.com/user-attachments/assets/da20b7b3-0eb3-4fcb-8da7-d09fcaa3de89" />
<img width="840" alt="Image" src="https://github.com/user-attachments/assets/1df62cc4-15d8-4079-a193-91e77abd2015" />

I am also able to view item sets that are not added as resources to the site in question. (This may be something we also discussed last time around.)

**Comment by kimisgold** [comment]
> I've just updated core, this module, and all my themes, and it appears we have lost the formatting of hierarchy pages to match the other browse pages:

@allanaaa I'm pretty sure this is theme-specific. Thanks Roy and Center Row have custom item browse views that need updating. I would not put that on Hierarchy to manage.

**Comment by allanaaa** [comment]
Wasn't it in Hierarchy in the first place? I can't see why we would've released 1.0 with unfinished browse pages.

**Comment by kimisgold** [comment]
@allanaaa What I mean is that Thanks Roy and Center Row have browse views that override markup from the core. Hierarchy's browse views are based off the core's latest version. 

Notably, the core combines the resource title and thumbnail into a single link to avoid tabbing through duplicate links. Thanks Roy and Center Row need to be updated accordingly.

**Comment by allanaaa** [comment]
Sorry, still confused. Why wouldn't Hierarchy base its browse views off the themes' overriding of the core?

**Comment by matthewjmckinley** [comment]
@allanaaa You're right, showing itemSets and associated items that are assigned to a grouping but NOT assigned to the site in public views is an oversight. 

I believe I've fixed this in the latest commit, and it seems like it may have also fixed the (private) appearance inconsistencies you mentioned? I can't replicate the inconsistency now, in any case. Give the lates code a go and see if these issues are resolved.

**Comment by kimisgold** [comment]
On the theme side, Thanks Roy and Center Row should have updated browse views that look consistent with Hierarchy.

**Comment by aviannamiller** [comment]
I am still seeing the issue @allanaaa pointed out on Lively. Private groupings are currently both hyperlinked and lacking the "Private" tag on hierarchy browse pages:

<img width="359" alt="Screenshot of a hierarchy tree. Some groupings in the trees show item counts while others do not, but all groupings display hyperlinks" src="https://github.com/user-attachments/assets/b7c5ce63-503a-47bc-afb3-19b22cbdb6fb" />

This appears to only impact Lively.

**Comment by matthewjmckinley** [comment]
@aviannamiller hm, I'm not able to recreate this. 

The Lively theme in my instance is responding correctly and un-linking/adding (Private) to groupings containing private itemSets. 

Are you running the latest code and have you cleared your cache/done a hard refresh of the page?

**Comment by matthewjmckinley** [comment]
OK I pushed some more fixes to the hierarchy.phtml and resource page block hierarchy display -- _hopefully_ everything displays corrrectly now, otherwise I can pull in Kim to see if it's a Lively issue?

**Comment by allanaaa** [comment]
That fixed the page block problems for me. I'm still seeing links and no "Private" on the hierarchy pages themselves, though they are appearing correctly on the item set page:

https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site-1/hierarchy/55

Everything looks good on Freedom.

**Comment by matthewjmckinley** [comment]
I still can't replicate -- @kimisgold , can you figure out why this seems to only be happening on Lively?

**Comment by kimisgold** [comment]
Lively has a custom Hierarchy view so that it can apply its custom details to the browse portion. It likely hasn't been keeping up to date with all the Hierarchy changes through this issue. If everything in core Hierarchy is pretty settled, then this would be a good time for Hierarchy to update or for a pull request with the changes to be submitted.

**Comment by matthewjmckinley** [comment]
My bad, I hadn't pulled the latest Lively code. I've now integrated the newer hierarchy.phtml changes to the custom lively view and submitted a PR.

**Comment by aviannamiller** [comment]
Lively is now behaving as anticipated! I am not seeing any remaining issues on my end.

**Comment by matthewjmckinley** [comment]
Great! I will close this issue and push a new Hierarchy release.
