### ISSUE TITLE
$siteItemSetArray is deprecated

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/Hierarchy#15]
Just to let you know there is a warning message when .htaccess is set as `SetEnv APPLICATION_ENV "development"`

In hierarchy public pages:

`Deprecated: Creation of dynamic property Hierarchy\View\Helper\HierarchyHelper::$siteItemSetArray is deprecated in /home/pwillaime/sites/arc_alpha/modules/Hierarchy/src/View/Helper/HierarchyHelper.php on line 188`

In item-set page in admin side (right panel):

<img width="455" height="495" alt="Image" src="https://github.com/user-attachments/assets/525c0502-c510-4c33-af34-e06aa05e24fa" />

**Comment by matthewjmckinley** [comment]
Whoops that caused a missing variable bug on admin side, fixed in https://github.com/omeka-s-modules/Hierarchy/commit/a8db844f0c0400278152c04218002c2a6b4295d7

**Comment by pprw** [comment]
Sorry but I still have this warning for a different line

On Omeka S 4. (master)

     Deprecated: Creation of dynamic property Hierarchy\View\Helper\HierarchyHelper::$siteItemSetArray is deprecated in /home/pwillaime/sites/arc_alpha/modules/Hierarchy/src/View/Helper/HierarchyHelper.php on line 193

On Omeka S  4.2.0-alpha.1 (develop)

    Warning: Undefined property: Hierarchy\View\Helper\HierarchyHelper::$siteItemSetArray in /home/pwillaime/sites/omeka-s/modules/Hierarchy/src/View/Helper/HierarchyHelper.php on line 225

**Comment by pprw** [comment]
Sorry to reopen this but I have still

    Deprecated: Creation of dynamic property Hierarchy\View\Helper\HierarchyHelper::$siteItemSetArray is deprecated in /home/pwillaime/sites/omeka-s/modules/Hierarchy/src/View/Helper/HierarchyHelper.php on line 261

Omeka S version 4.2.0-alpha.1 (develop) and theme default up-to-date (v1.9.1)
